// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMGIfAsN7rXy0mgM4cLL10kECqE-9NjjU',
    appId: '1:874772295278:web:728c009fd08c99a2fd407f',
    messagingSenderId: '874772295278',
    projectId: 'hand-sign-app',
    authDomain: 'hand-sign-app.firebaseapp.com',
    storageBucket: 'hand-sign-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzidwwvVOimOWRZ0--I5097wyGAOSKL-Q',
    appId: '1:874772295278:android:391ad731c5f2535bfd407f',
    messagingSenderId: '874772295278',
    projectId: 'hand-sign-app',
    storageBucket: 'hand-sign-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUUrs62ee7MPipV-UxRIPhai9xQvjtYBo',
    appId: '1:874772295278:ios:868cc1a92fbdab6afd407f',
    messagingSenderId: '874772295278',
    projectId: 'hand-sign-app',
    storageBucket: 'hand-sign-app.firebasestorage.app',
    iosBundleId: 'com.example.handSign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUUrs62ee7MPipV-UxRIPhai9xQvjtYBo',
    appId: '1:874772295278:ios:868cc1a92fbdab6afd407f',
    messagingSenderId: '874772295278',
    projectId: 'hand-sign-app',
    storageBucket: 'hand-sign-app.firebasestorage.app',
    iosBundleId: 'com.example.handSign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMGIfAsN7rXy0mgM4cLL10kECqE-9NjjU',
    appId: '1:874772295278:web:8539c92a855d32b7fd407f',
    messagingSenderId: '874772295278',
    projectId: 'hand-sign-app',
    authDomain: 'hand-sign-app.firebaseapp.com',
    storageBucket: 'hand-sign-app.firebasestorage.app',
  );
}
